import { useEffect, useState } from 'react'
import Carousel from 'react-multi-carousel'

import { FiArrowUpRight, FiArrowRight } from 'react-icons/fi'
import { SlArrowRight, SlArrowLeft } from 'react-icons/sl'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '@/styles/Home.module.scss'

import campusImg from '@/assets/images/campus.jpg'
import facultyImage1 from '@/assets/images/facultyImage1.jpg'
import research1 from '@/assets/images/research1.jpg'
import research2 from '@/assets/images/research2.jpg'
import research3 from '@/assets/images/research3.jpg'

export default function Home() {
  const [courseCarouselLevel, setCourseCarouselLevel] = useState(0)

  const CarouselArrowButtons = ({ props }) => {
    console.log("PROPS: ", props);
    return (
      <div>
        <button>{">"}</button>
        <button>{"<"}</button>
        <button>{"-"}</button>
      </div>
    )
  }

  const ButtonGroup = ({ next, previous, goToSlide, resetState, ...rest }) => {
    useEffect(() => {
      if (resetState)
        goToSlide(0);
    }, [resetState])
    return (
      <div className={styles.carouselBtnGroup}>
        <button onClick={() => previous()}><SlArrowLeft /></button>
        <button onClick={() => next()}><SlArrowRight /></button>
      </div>    
    );
  };

  const carouselSettings = {
    ssr: true,
    draggable: true,
    partialVisible: true,
    showDots: false,
    slidesToSlide: 1,
    swipeable: false,
    containerClass: styles.carouselContainer,
    sliderClass: styles.carouselSlider,
    responsive: {
      desktop: {
        breakpoint: { max: 3000, min: 1024 },
        items: 3,
        slidesToSlide: 1,
        partialVisibilityGutter: 40
      },
      tablet: {
        breakpoint: { max: 1024, min: 464 },
        items: 2,
        slidesToSlide: 1  
      },
      mobile: {
        breakpoint: { max: 464, min: 0 },
        items: 1,
        slidesToSlide: 1
      }
    }
  }

  const bachelorCourseData = [
    {
      title: "Food and Nutrition"
    },
    {
      title: "Human Development and Family Studies"
    },
    {
      title: "Extension Education & Communication Management"
    },
    {
      title: "Textile and Apparel Designing"
    },
    {
      title: "Resource Management and Consumer Science"
    }
  ]

  return (
    <>
      <Head>
        <title>University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.introCarousel}>
        <div className={styles.heroImage}>
          <Image src={campusImg} alt="university campus"/>
        </div>
        <div className={styles.infoContainer}>
          <span>
            <h1>College of <br /> Community Science</h1>
            <p>विद्या ददाति विनयम</p>
          </span>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi aperiam placeat veritatis adipisci laboriosam nihil ex cum, inventore beatae repellendus quo aut eius necessitatibus illum.
          </p>
        </div>
      </section>

      {/* Faculty Section */}
      <section className={styles.facultySection}>
        <div className={styles.header}>
          <p>FACULTY</p>
          <h2>OUR SKILLED FACULTY HELPS STUDENTS IN MANY DISCIPLINES</h2>
        </div>
        <div className={styles.infoGrid}>

          <Image src={facultyImage1} alt="faculty image" width='1rem' height={'2rem'} data-aos="fade-up" />
          <div data-aos="fade-up" data-aos-delay="250">
            <h1>Faculty of Community Science</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur cumque aliquam nisi debitis consectetur. Corrupti suscipit necessitatibus rem eligendi blanditiis?</p>
            <Link href="#">Learn More</Link>
          </div>

          <div data-aos="fade-up">
            <h1>Faculty of Food, Nutrition & Dietetics</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur cumque aliquam nisi debitis consectetur. Corrupti suscipit necessitatibus rem eligendi blanditiis?</p>
            <Link href="#">Learn More</Link>
          </div>
          <Image src={facultyImage1} alt="faculty image" data-aos="fade-up" data-aos-delay="250" />

        </div>

        <Link href="#" className={styles.moreBtn}>SEE ALL FACULTY <FiArrowUpRight /></Link>
      </section>

      {/* Research Section */}
      <section className={styles.researchSection}>
        <div className={styles.header}>
          <h2>OUR RECENT RESEARCH & <br /> PUBLICATIONS</h2>
          <p>RESEARCH</p>
        </div>

        {/* <div className={styles.researchSliderContainer}> */}
          <Carousel {...carouselSettings} arrows={false} renderButtonGroupOutside={true} customButtonGroup={<ButtonGroup resetState={courseCarouselLevel} />}>
            <div className={styles.researchCard} data-aos="fade-left">
              <Image src={research1} alt="research image"/>
              <h1>Food & Nutrition Research Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard} data-aos="fade-left" data-aos-delay="250">
              <Image src={research2} alt="research image"/>
              <h1>Human Development & Family Studies</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard} data-aos="fade-left" data-aos-delay="500">
              <Image src={research3} alt="research image"/>
              <h1>Extension Education & Communication Management</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard} data-aos="fade-left" data-aos-delay="750">
              <Image src={research1} alt="research image"/>
              <h1>Food & Nutrition Research Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard}>
              <Image src={research2} alt="research image"/>
              <h1>Human Development & Family Studies</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard}>
              <Image src={research3} alt="research image"/>
              <h1>Extension Education & Communication Management</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
          </Carousel>
        {/* </div> */}

        <Link href="#" className={styles.moreBtn}>SEE ALL RESEARCH <FiArrowUpRight /></Link>
      </section>

      {/* Academic Section */}
      <section className={styles.academicSection}>
        <div className={styles.header}>
          <p>ACADEMICS</p>
          <span>
            <h2>ACADEMIC PROGRAMS</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. <br /> Vel, distinctio aperiam! Ab, corporis. Saepe, distinctio!</p>
          </span>
        </div>

        <div className={styles.courseContainer}>
          <ul className={styles.courseTabs}>
            <li className={courseCarouselLevel === 0 ? styles.selected : ''} onClick={() => setCourseCarouselLevel(0)}>/Bachelor</li>
            <li className={courseCarouselLevel === 1 ? styles.selected : ''} onClick={() => setCourseCarouselLevel(1)}>/Master</li>
            <li className={courseCarouselLevel === 2 ? styles.selected : ''} onClick={() => setCourseCarouselLevel(2)}>/PhD</li>
          </ul>

          <Carousel {...carouselSettings} arrows={false} renderButtonGroupOutside={true} customButtonGroup={<ButtonGroup resetState={courseCarouselLevel} />}>
            {courseCarouselLevel === 0 && bachelorCourseData.map((item, i) => {
              return (
                <div className={styles.courseCard} key={i} data-aos="fade-left" data-aos-delay={250 * i}>
                  <h1>{item.title}</h1>
                  <div className={styles.cardFooter}>
                    <span>/Bachelor</span>
                    <Link href="#"><FiArrowRight /></Link>
                  </div>
                </div>
              )
            })}
            {courseCarouselLevel === 1 && bachelorCourseData.map((item, i) => {
              return (
                <div className={styles.courseCard} key={i} data-aos="fade-left" data-aos-delay={250 * i}>
                  <h1>{item.title}</h1>
                  <div className={styles.cardFooter}>
                    <span>/Master</span>
                    <Link href="#"><FiArrowRight /></Link>
                  </div>
                </div>
              )
            })}
            {courseCarouselLevel === 2 && bachelorCourseData.map((item, i) => {
              return (
                <div className={styles.courseCard} key={i} data-aos="fade-left" data-aos-delay={250 * i}>
                  <h1>{item.title}</h1>
                  <div className={styles.cardFooter}>
                    <span>/Phd</span>
                    <Link href="#"><FiArrowRight /></Link>
                  </div>
                </div>
              )
            })}
          </Carousel>
        </div>
      </section>
    </>
  )
}
