import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '@/styles/Home.module.scss'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

import campusImg from '@/assets/images/campus.jpg'
import facultyImage1 from '@/assets/images/facultyImage1.jpg'
import research1 from '@/assets/images/research1.jpg'
import research2 from '@/assets/images/research2.jpg'
import research3 from '@/assets/images/research3.jpg'

import { FiArrowUpRight } from 'react-icons/fi'

import Slider from "react-slick"

export default function Home() {
  const sliderSettings = {
    dots: false,
    infinite: false,
    speed: 750,
    slidesToShow: 3,
    slidesToScroll: 1,
    arrows: false,
    focusOnSelect: false,
    easing: 'ease'
  };

  return (
    <>
      <Head>
        <title>University</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.introCarousel}>
        <div className={styles.heroImage}>
          <Image src={campusImg} />
        </div>
        <div className={styles.infoContainer}>
          <span>
            <h1>College of <br /> Community Science</h1>
            <p>विद्या ददाति विनयम</p>
          </span>
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Modi aperiam placeat veritatis adipisci laboriosam nihil ex cum, inventore beatae repellendus quo aut eius necessitatibus illum.
          </p>
        </div>
      </section>

      {/* Faculty Section */}
      <section className={styles.facultySection}>
        <div className={styles.header}>
          <p>FACULTY</p>
          <h2>OUR SKILLED FACULTY HELPS STUDENTS IN MANY DISCIPLINES</h2>
        </div>
        <div className={styles.infoGrid}>

          <Image src={facultyImage1} width='1rem' height={'2rem'} data-aos="fade-up"/>
          <div data-aos="fade-up" data-aos-delay="250">
            <h1>Faculty of Community Science</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur cumque aliquam nisi debitis consectetur. Corrupti suscipit necessitatibus rem eligendi blanditiis?</p>
            <Link href="#">Learn More</Link>
          </div>

          <div data-aos="fade-up">
            <h1>Faculty of Food, Nutrition & Dietetics</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur cumque aliquam nisi debitis consectetur. Corrupti suscipit necessitatibus rem eligendi blanditiis?</p>
            <Link href="#">Learn More</Link>
          </div>
          <Image src={facultyImage1} data-aos="fade-up" data-aos-delay="250"/>

        </div>

        <Link href="#" className={styles.moreBtn}>SEE ALL FACULTY <FiArrowUpRight /></Link>
      </section>

      {/* Research Section */}
      <section className={styles.researchSection}>
        <div className={styles.header}>
          <h2>OUR RECENT RESEARCH & <br/> PUBLICATIONS</h2>
          <p>RESEARCH</p>
        </div>

        <div className={styles.researchSliderContainer}>
          <Slider {...sliderSettings}>
            <div className={styles.researchCard} data-aos="fade-left">
              <Image src={research1} />
              <h1>Food & Nutrition Research Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard} data-aos="fade-left" data-aos-delay="250">
              <Image src={research2}/>
              <h1>Human Development & Family Studies</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard} data-aos="fade-left" data-aos-delay="500">
              <Image src={research3}/>
              <h1>Extension Education & Communication Management</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard}>
              <Image src={research1} />
              <h1>Food & Nutrition Research Title</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard}>
              <Image src={research2}/>
              <h1>Human Development & Family Studies</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
            <div className={styles.researchCard}>
              <Image src={research3}/>
              <h1>Extension Education & Communication Management</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque laborum ex accusamus commodi possimus voluptas itaque id facere assumenda, architecto cupiditate aperiam magni sint alias.</p>
            </div>
          </Slider>
        </div>

        <Link href="#" className={styles.moreBtn}>SEE ALL RESEARCH <FiArrowUpRight /></Link>
      </section>

      {/* Academic Section */}
      <section className={styles.academicSection}>
        <div className={styles.header}>
          <h2>ACADEMIC PROGRAMS</h2>
          <p>ACADEMICS</p>
        </div>
      </section>
    </>
  )
}
